"""empty message

Revision ID: 008105bde47c
Revises: 6ef2a623c3a0
Create Date: 2018-07-03 20:10:54.768884

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '008105bde47c'
down_revision = '6ef2a623c3a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('desc', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reviews', 'desc')
    # ### end Alembic commands ###
