"""empty message

Revision ID: 19433ec2e58b
Revises: a52392e288d9
Create Date: 2018-04-01 18:23:35.072997

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19433ec2e58b'
down_revision = 'a52392e288d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blacklist_token', sa.Column('revoked', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blacklist_token', 'revoked')
    # ### end Alembic commands ###
