"""empty message

Revision ID: 277b3d313965
Revises: c72f17b6c7cf
Create Date: 2018-06-28 16:10:40.140137

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '277b3d313965'
down_revision = 'c72f17b6c7cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('descr', sa.String(), nullable=False))
    op.drop_column('reviews', 'description')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('description', sa.VARCHAR(length=256), autoincrement=False, nullable=False))
    op.drop_column('reviews', 'descr')
    # ### end Alembic commands ###
