"""empty message

Revision ID: 365085936607
Revises: e7c7c04b969c
Create Date: 2018-07-03 20:26:57.526031

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '365085936607'
down_revision = 'e7c7c04b969c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('business', sa.Column('description', sa.String(), nullable=False))
    op.drop_column('business', 'desc')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('business', sa.Column('desc', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('business', 'description')
    # ### end Alembic commands ###
