"""empty message

Revision ID: 3d28ba255156
Revises: 277b3d313965
Create Date: 2018-06-28 16:11:09.437334

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d28ba255156'
down_revision = '277b3d313965'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('description', sa.String(), nullable=False))
    op.drop_column('reviews', 'descr')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('descr', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('reviews', 'description')
    # ### end Alembic commands ###
