"""empty message

Revision ID: 6309917f7ca4
Revises: 7246d3169270
Create Date: 2018-07-03 20:16:44.570674

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6309917f7ca4'
down_revision = '7246d3169270'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('desc', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reviews', 'desc')
    # ### end Alembic commands ###
