"""empty message

Revision ID: 6ef2a623c3a0
Revises: cef7f8b52f1d
Create Date: 2018-07-03 19:50:51.718001

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ef2a623c3a0'
down_revision = 'cef7f8b52f1d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('business', sa.Column('description', sa.String(), nullable=False))
    op.drop_column('business', 'descriptio')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('business', sa.Column('descriptio', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('business', 'description')
    # ### end Alembic commands ###
