"""empty message

Revision ID: 7246d3169270
Revises: 008105bde47c
Create Date: 2018-07-03 20:11:24.152671

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7246d3169270'
down_revision = '008105bde47c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reviews', 'desc')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('desc', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
