"""empty message

Revision ID: a52392e288d9
Revises: 0bf6c69cf2a4
Create Date: 2018-03-31 04:24:03.846485

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a52392e288d9'
down_revision = '0bf6c69cf2a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('update_pass', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'update_pass')
    # ### end Alembic commands ###
