"""empty message

Revision ID: daf68fd7177e
Revises: 6309917f7ca4
Create Date: 2018-07-03 20:19:04.016651

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'daf68fd7177e'
down_revision = '6309917f7ca4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reviews', 'desc')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('desc', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
