"""empty message

Revision ID: e7c7c04b969c
Revises: daf68fd7177e
Create Date: 2018-07-03 20:23:06.108653

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7c7c04b969c'
down_revision = 'daf68fd7177e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('business', sa.Column('desc', sa.String(), nullable=True))
    op.drop_column('business', 'description')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('business', sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('business', 'desc')
    # ### end Alembic commands ###
